/* =========================================================
   NEXUS — LEGAL & COMPLIANCE MODAL ENGINE
   Terms of Service, Privacy Policy, Community Guidelines, and License
   ========================================================= */

(function () {
  const licenseText = `NEXUS ENTERPRISE PROPRIETARY LICENSE

Copyright © 2026 NEXUS. All Rights Reserved.

This software, its source code, user interface design, graphics, cryptographic verification systems, documentation, and operational data architecture are proprietary intellectual property of NEXUS and Aryan Sharma.

1. PROHIBITED ACTS: No entity or individual is granted permission to copy, reverse-engineer, decompile, redistribute, sublicense, lease, or publicly broadcast any portion of this software without an explicit written license agreement signed by the copyright owner.

2. COMMERCIAL APPLICATION: This platform is licensed strictly for authorized internal business operations. Unauthorized commercial mirroring, white-labeling, or extraction is strictly prohibited and subject to maximum legal penalties under international copyright treaties.

3. GOVERNING LAW: This license shall be governed and construed in accordance with international intellectual property laws and applicable commercial codes.`;

  const termsHtml = `
    <div class="nexus-legal-page">
      <h3>1. Agreement to Terms</h3>
      <p>By accessing or utilizing NEXUS, you agree to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.</p>

      <h3>2. Workspace & Authentication</h3>
      <p>You are responsible for safeguarding your account credentials, JSON Web Tokens (JWT), and API keys. Any action performed under your authorized session is deemed to have been executed by your authorized enterprise representatives.</p>

      <h3>3. Financial Integrity & Invoicing</h3>
      <p>Invoices issued through NEXUS contain immutable cryptographic HMAC-SHA256 signatures and QR authenticity proofs. You agree not to tamper with, forge, or alter digital verification digests generated by the system.</p>

      <h3>4. Multi-Warehouse Stock & Orders</h3>
      <p>NEXUS operates atomic database transactions to guarantee stock consistency. You agree to utilize order and inventory transfer APIs in accordance with operational limits and concurrency guidelines.</p>

      <h3>5. System Uptime & Service Levels</h3>
      <p>NEXUS strives for 99.99% operational uptime across its REST Gateway and FastAPI Intelligence Engine. Scheduled maintenance windows will be communicated via notification channels.</p>
    </div>
  `;

  const privacyHtml = `
    <div class="nexus-legal-page">
      <h3>1. Data Collection & Processing</h3>
      <p>NEXUS processes customer profiles, transaction ledgers, inventory records, and financial accounts strictly for enterprise resource planning, billing, and predictive analytics.</p>

      <h3>2. Cryptographic Security</h3>
      <p>All sensitive authentication tokens and passwords are encrypted using bcrypt hashing (10 rounds). Database communications and external API requests are guarded by standard TLS encryption and constant-time signature verifications.</p>

      <h3>3. Analytics & Machine Learning</h3>
      <p>Historical demand figures and sales numbers processed by the Python Intelligence Engine are analyzed in isolated environments and never shared with third parties or external advertising networks.</p>

      <h3>4. Data Ownership & Portability</h3>
      <p>Your enterprise maintains 100% ownership over all uploaded catalogs, customer lists, order records, and invoices. Data can be exported at any time via integrated XLSX (SheetJS) and PDF export tools.</p>
    </div>
  `;

  const guidelinesHtml = `
    <div class="nexus-legal-page">
      <h3>1. Professional Workspace Conduct</h3>
      <p>NEXUS is an enterprise-grade commercial operating system. Users within shared team workspaces must maintain professional communication, accurate financial bookkeeping, and authentic customer documentation.</p>

      <h3>2. Acceptable Use Standards</h3>
      <p>Do not upload fraudulent tax identifiers, forged invoices, prohibited contraband catalogs, or malicious script payloads into customer or product notes.</p>

      <h3>3. Access Control & Role Management</h3>
      <p>Workspace Owners and Administrators should adhere to the principle of least privilege when assigning team roles (Sales Lead, Inventory Manager, Finance Lead) to protect sensitive company metrics.</p>

      <h3>4. Audit Trails & Compliance</h3>
      <p>All inventory adjustments, warehouse transfers, invoice status changes, and pipeline deal modifications are logged to maintain an accountable internal audit trail.</p>
    </div>
  `;

  function openLegal(kind) {
    if (typeof openModal !== 'function') return;

    if (kind === 'license') {
      openModal(
        'Proprietary License',
        'NEXUS Intellectual Property and License Terms.',
        `<div class="nexus-legal-page"><div class="nexus-license-box">${typeof esc === 'function' ? esc(licenseText) : licenseText}</div></div>`,
        `<button class="btn btn-ghost btn-sm" type="button" data-close-modal>Close</button>`,
        false
      );
    } else if (kind === 'privacy') {
      openModal(
        'Privacy Policy',
        'Enterprise data handling, encryption, and confidentiality standards.',
        privacyHtml,
        `<button class="btn btn-ghost btn-sm" type="button" data-close-modal>Close</button>`,
        false
      );
    } else if (kind === 'guidelines') {
      openModal(
        'Community & Workspace Guidelines',
        'Operational rules, role governance, and audit compliance.',
        guidelinesHtml,
        `<button class="btn btn-ghost btn-sm" type="button" data-close-modal>Close</button>`,
        false
      );
    } else {
      openModal(
        'Terms of Service',
        'Commercial platform terms and operational policies.',
        termsHtml,
        `<button class="btn btn-ghost btn-sm" type="button" data-close-modal>Close</button>`,
        false
      );
    }
  }

  window.openLegal = openLegal;

  document.addEventListener('click', function (e) {
    const legalTrigger = e.target.closest('[data-legal-open]');
    if (legalTrigger) {
      e.preventDefault();
      openLegal(legalTrigger.dataset.legalOpen);
      return;
    }

    if (e.target.closest('[data-nexus-license]')) {
      e.preventDefault();
      openLegal('license');
      return;
    }

    if (e.target.closest('[data-nexus-terms]')) {
      e.preventDefault();
      openLegal('terms');
      return;
    }

    if (e.target.closest('[data-nexus-privacy]')) {
      e.preventDefault();
      openLegal('privacy');
      return;
    }

    if (e.target.closest('[data-nexus-guidelines]')) {
      e.preventDefault();
      openLegal('guidelines');
      return;
    }
  });

  function addLegalSettings() {
    const settings = document.querySelector('#screen-settings');
    if (!settings || settings.querySelector('.nexus-settings-legal')) return;

    const block = document.createElement('div');
    block.className = 'nexus-settings-legal';
    block.innerHTML = `
      <div class="nx-settings-section-title">Compliance & Legal Policies</div>
      <div class="nexus-settings-legal-row">
        <div>
          <div class="nexus-settings-legal-title">NEXUS Enterprise Operating Platform</div>
          <div class="nexus-settings-legal-copy">© 2026 NEXUS · Cryptographic Invoicing · ACID Relational Architecture</div>
        </div>
        <div class="nexus-settings-legal-actions">
          <button type="button" class="btn btn-ghost btn-sm" data-legal-open="terms">Terms of Service</button>
          <button type="button" class="btn btn-ghost btn-sm" data-legal-open="privacy">Privacy Policy</button>
          <button type="button" class="btn btn-ghost btn-sm" data-legal-open="guidelines">Community Guidelines</button>
          <button type="button" class="btn btn-ghost btn-sm" data-legal-open="license">Proprietary License</button>
        </div>
      </div>`;
    settings.appendChild(block);
  }

  const observer = new MutationObserver(addLegalSettings);
  observer.observe(document.body, { childList: true, subtree: true });
  addLegalSettings();
})();
